version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      AWS_DEFAULT_REGION: "eu-west-1"

    steps:
      - checkout
      - run: make all
